ecore_fb: fix build with tslib
Build with tslib is broken since version 1.25.0 and
https://git.enlightenment.org/core/efl.git/commit/?id=8e3606698eb439eecd7302a885504365aca7e564:

/data/buildroot-autobuilder/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/powerpc-buildroot-linux-uclibc/9.3.0/../../../../powerpc-buildroot-linux-uclibc/bin/ld: src/lib/ecore_fb/libecore_fb.so.1.25.1.p/ecore_fb_ts.c.o: in function `_ecore_fb_ts_fd_handler':
ecore_fb_ts.c:(.text+0x4c): undefined reference to `ts_read_raw'

Fixes:
 - http://autobuild.buildroot.org/results/fa111306b95316eed54771550474dae804fa261e

Signed-off-by: Fabrice Fontaine <fontaine.fabrice@gmail.com>